static MAIN_TABLE: [OpcodeEntry; 256] = [
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::LdR16V16(R16::BC), length: 3, cycles: 12 },
    OpcodeEntry { opcode: Opcode::LdPtrR16R8(R16::BC, R8::A), length: 1, cycles: 8 },
    OpcodeEntry { opcode: Opcode::IncR16(R16::BC), length: 1, cycles: 8 },
    OpcodeEntry { opcode: Opcode::IncR8(R8::B), length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::DecR8(R8::B), length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::LdR8V8(R8::B), length: 2, cycles: 8 },
    OpcodeEntry { opcode: Opcode::RlcA, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::LdPtrV16R16(R16::SP), length: 3, cycles: 20 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
];

pub enum R8 {
    A, B, C, D, E, H, L, HLIndirect
}

pub enum R16 {
    AF, BC, DE, HL, SP, PC
}

pub enum CC {
    NZ,
    Z,
    NC,
    C,
}

pub enum Opcode {
    AdcR8R8(R8, R8),
    AdcR8V8(R8),
    AddR8R8(R8, R8),
    AddR8V8(R8),
    AddR16V16(R16),
    AddR16R16(R16, R16),
    AddSPE8,
    AndR8R8(R8, R8),
    AndR8V8(R8),
    Bit(R8),
    CallV16,
    CallCCV16(CC),
    Ccf,
    CpR8R8(R8, R8),
    CpR8PtrR16(R8, R16),
    CpR8V8(R8),
    Cpl,
    Daa,
    DecR8(R8),
    DecPtrR16(R16),
    DecR16(R16),
    Di,
    Ei,
    Halt,
    IncR8(R8),
    IncPtrR16(R16),
    IncR16(R16),
    JpV16,
    JpCCV16(CC),
    JpR16(R16),
    JrV16,
    JrCCV16,
    LdR8R8(R8, R8), // load value in right reg to left reg
    LdR8V8(R8), // load value to reg
    LdR16V16(R16), // load value in right reg to left reg
    LdPtrR16R8(R16, R8),
    LdPtrV16R8(R8),
    LdHPtrV16R8(R8), // load a to v16 but on page 0xff00 + v16
    LdHPtrR8R8(R8, R8), // loads a to byte pointer by 0xff00 + c
    LdR8PtrR16(R8, R16), // loads value from address reg into A
    LdR8PtrV16(R8), // loads value from address val into A
    LdHR8PtrV16(R8), // loads value from address 0xff00 + val into A
    LdHR8PtrR8(R8, R8),
    LdPtrHLiR8(R8), // increment
    LdPtrHLdR8(R8), // decrement
    LdR8PtrHLd(R8),
    LdR8PtrHLi(R8),
    LdPtrV16R16(R16),
    LdHLSPe8, // add signed e8 to SP and result in HL
    LdR16R16(R16, R16),
    Nop,
    OrR8R8(R8,R8),
    OrR8V8(R8),
    PopR16(R16),
    PushR16(R16),
    Res(R8),
    Ret,
    RetCC(CC),
    Reti,
    RlR8(R8),
    RlcR8(R8),
    RlcA,
    RrR8(R8),
    RrcR8(R8),
    RstV16,
    SbcR8R8(R8, R8),
    SbcR8V8(R8),
    Scf,
    Set(R8),
    SlaR8(R8),
    SraR8(R8),
    SrlR8(R8),
    Stop,
    SubR8R8(R8, R8),
    SubR8V8(R8),
    SwapR8(R8),
    XorR8(R8),
    XorR8V8(R8)
}

pub struct OpcodeEntry {
    opcode: Opcode,
    length: u8,
    cycles: u8,
}

pub fn decode(byte: u8) -> &'static OpcodeEntry {
    &MAIN_TABLE[byte as usize]
}