static LOOKUP: [OpcodeEntry; 256] = [
    // 0x00
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::LdR16N16(R16::BC), length: 3, cycles: 12 },
    OpcodeEntry { opcode: Opcode::LdPtrR16A(R16::BC), length: 1, cycles: 8 },
    OpcodeEntry { opcode: Opcode::IncR16(R16::BC), length: 1, cycles: 8 },
    OpcodeEntry { opcode: Opcode::IncR8(R8::B), length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::DecR8(R8::B), length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::LdR8V8(R8::B), length: 2, cycles: 8 },
    OpcodeEntry { opcode: Opcode::RlcA, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::LdPtrN16SP, length: 3, cycles: 20 },
    OpcodeEntry { opcode: Opcode::AddHLR16(R16::BC), length: 1, cycles: 8 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    // 0x0f
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    // 0x1f
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
    OpcodeEntry { opcode: Opcode::Nop, length: 1, cycles: 4 },
];

pub enum R8 {
    A, B, C, D, E, H, L, HLIndirect
}

pub enum R16 {
    AF, BC, DE, HL, SP, PC
}

pub enum CC {
    NZ,
    Z,
    NC,
    C,
}

pub enum Opcode {
    // Load
    LdR8R8(R8, R8), // load value in right reg to left reg
    LdR8V8(R8), // load value to reg
    LdR16N16(R16), // load value in right reg to left reg
    LdPtrR16A(R16),
    LdPtrN16A,
    LdHPtrN16A, // load a to N16 but on page 0xff00 + N16
    LdHPtrCA, // loads a to byte pointer by 0xff00 + c
    LdAPtrR16(R16), // loads value from address reg into A
    LdAPtrN16, // loads value from address val into A
    LdHAPtrN16, // loads value from address 0xff00 + val into A
    LdHAPtrC,
    LdPtrHLIncA, // increment
    LdPtrHLDecA, // decrement
    LdAPtrHLDec,
    LdAPtrHLInc,
    // 8-bit arithmetic
    AdcAR8(R8),
    AdcAV8,
    AddAR8(R8),
    AddAV8,
    CpAR8(R8),
    CpAV8,
    DecR8(R8),
    IncR8(R8),
    SbcAR8(R8),
    SbcAV8,
    SubAR8(R8),
    SubAV8,
    // 16-bit arithmetic
    AddHLR16(R16),
    DecR16(R16),
    IncR16(R16),
    // Bitwise logic
    AndAR8(R8),
    AndAV8,
    Cpl,
    OrAR8(R8),
    OrAV8,
    XorAR8(R8),
    XorAV8,
    // Bit flag
    Bit(R8),
    Set(R8),
    Res(R8),
    // Bit shift
    RlR8(R8),
    RlA,
    RlcR8(R8),
    RlcA,
    RrR8(R8),
    RrA,
    RrcR8(R8),
    RrcA,
    SlaR8(R8),
    SraR8(R8),
    SrlR8(R8),
    SwapR8(R8),
    // Jump / coroutine
    CallN16,
    CallCCN16(CC),
    JpHL,
    JpN16,
    JpCCN16(CC),
    JrE8,
    JrCCE8(CC),
    Ret,
    RetCC(CC),
    Reti,
    Rst(u8),
    // Carry flag
    Scf,
    Ccf,
    // Stack manipulation
    AddHLSP,
    AddSPe8,
    LdHLSPe8, // add signed e8 to SP and result in HL
    DecSP,
    IncSP,
    LdSPN16,
    LdPtrN16SP, 
    LdSPHL,
    PopAF,
    PopR16(R16),
    PushAF,
    PushR16(R16),
    // Interrupts
    Di,
    Ei,
    Halt,
    // Misc
    Daa,
    Nop,
    Stop,
}

pub struct OpcodeEntry {
    opcode: Opcode,
    length: u8,
    cycles: u8,
}

pub fn decode(byte: u8) -> &'static OpcodeEntry {
    &LOOKUP[byte as usize]
}