use crate::cpu::decoder::{OpcodeEntry, Opcode};
use crate::cpu::Cpu;

impl Cpu {
    pub fn execute_instruction(&mut self, entry: &OpcodeEntry) {
        match &entry.opcode {
            Opcode::LdR8R8(r8, r9) => todo!(),
            Opcode::LdR8N8(r8) => todo!(),
            Opcode::LdR16N16(r16) => todo!(),
            Opcode::LdPtrR16A(r16) => todo!(),
            Opcode::LdPtrN16A => todo!(),
            Opcode::LdHPtrCA => todo!(),
            Opcode::LdAPtrR16(r16) => todo!(),
            Opcode::LdAPtrN16 => todo!(),
            Opcode::LdHAPtrN16 => todo!(),
            Opcode::LdHAPtrC => todo!(),
            Opcode::LDHAPtrN8 => todo!(),
            Opcode::LDHPtrN8A => todo!(),
            Opcode::LdPtrHLIncA => todo!(),
            Opcode::LdPtrHLDecA => todo!(),
            Opcode::LdAPtrHLDec => todo!(),
            Opcode::LdAPtrHLInc => todo!(),
            Opcode::AdcAR8(r8) => todo!(),
            Opcode::AdcAN8 => todo!(),
            Opcode::AddAR8(r8) => todo!(),
            Opcode::AddAN8 => todo!(),
            Opcode::CpAR8(r8) => todo!(),
            Opcode::CpAN8 => todo!(),
            Opcode::DecR8(r8) => todo!(),
            Opcode::IncR8(r8) => todo!(),
            Opcode::SbcAR8(r8) => todo!(),
            Opcode::SbcAN8 => todo!(),
            Opcode::SubAR8(r8) => todo!(),
            Opcode::SubAN8 => todo!(),
            Opcode::AddHLR16(r16) => todo!(),
            Opcode::DecR16(r16) => todo!(),
            Opcode::IncR16(r16) => todo!(),
            Opcode::AndAR8(r8) => todo!(),
            Opcode::AndAN8 => todo!(),
            Opcode::Cpl => todo!(),
            Opcode::OrAR8(r8) => todo!(),
            Opcode::OrAN8 => todo!(),
            Opcode::XorAR8(r8) => todo!(),
            Opcode::XorAN8 => todo!(),
            Opcode::Bit(_, r8) => todo!(),
            Opcode::Set(_, r8) => todo!(),
            Opcode::Res(_, r8) => todo!(),
            Opcode::RlR8(r8) => todo!(),
            Opcode::RlA => todo!(),
            Opcode::RlcR8(r8) => todo!(),
            Opcode::RlcA => todo!(),
            Opcode::RrR8(r8) => todo!(),
            Opcode::RrA => todo!(),
            Opcode::RrcR8(r8) => todo!(),
            Opcode::RrcA => todo!(),
            Opcode::SlaR8(r8) => todo!(),
            Opcode::SraR8(r8) => todo!(),
            Opcode::SrlR8(r8) => todo!(),
            Opcode::SwapR8(r8) => todo!(),
            Opcode::CallN16 => todo!(),
            Opcode::CallCCN16(cc) => todo!(),
            Opcode::JpHL => todo!(),
            Opcode::JpN16 => todo!(),
            Opcode::JpCCN16(cc) => todo!(),
            Opcode::JrE8 => todo!(),
            Opcode::JrCCE8(cc) => todo!(),
            Opcode::Ret => todo!(),
            Opcode::RetCC(cc) => todo!(),
            Opcode::RetI => todo!(),
            Opcode::Rst(_) => todo!(),
            Opcode::Scf => todo!(),
            Opcode::Ccf => todo!(),
            Opcode::AddHLSP => todo!(),
            Opcode::AddSPe8 => todo!(),
            Opcode::LdHLSPe8 => todo!(),
            Opcode::DecSP => todo!(),
            Opcode::IncSP => todo!(),
            Opcode::LdSPN16 => todo!(),
            Opcode::LdPtrN16SP => todo!(),
            Opcode::LdSPHL => todo!(),
            Opcode::PopAF => todo!(),
            Opcode::PopR16(r16) => todo!(),
            Opcode::PushAF => todo!(),
            Opcode::PushR16(r16) => todo!(),
            Opcode::Di => todo!(),
            Opcode::Ei => todo!(),
            Opcode::Halt => todo!(),
            Opcode::Daa => todo!(),
            Opcode::Nop => todo!(),
            Opcode::Stop => todo!(),
            Opcode::Undefined => todo!(),
            Opcode::Prefix => todo!(),
        }
    }
}