use crate::cpu::decoder::{OpcodeEntry, Opcode};
use crate::cpu::Cpu;
use crate::mmu::Mmu;

impl Cpu {
    pub fn execute_instruction(&mut self, entry: &OpcodeEntry, mmu: &Mmu) {
        match &entry.opcode {
            Opcode::LdR8R8(r8, r9) => {},
            Opcode::LdR8N8(r8) => {},
            Opcode::LdR16N16(r16) => {},
            Opcode::LdPtrR16A(r16) => {},
            Opcode::LdPtrN16A => {},
            Opcode::LdHPtrCA => {},
            Opcode::LdAPtrR16(r16) => {},
            Opcode::LdAPtrN16 => {},
            Opcode::LdHAPtrN16 => {},
            Opcode::LdHAPtrC => {},
            Opcode::LDHAPtrN8 => {},
            Opcode::LDHPtrN8A => {},
            Opcode::LdPtrHLIncA => {},
            Opcode::LdPtrHLDecA => {},
            Opcode::LdAPtrHLDec => {},
            Opcode::LdAPtrHLInc => {},
            Opcode::AdcAR8(r8) => {},
            Opcode::AdcAN8 => {},
            Opcode::AddAR8(r8) => {},
            Opcode::AddAN8 => {},
            Opcode::CpAR8(r8) => {},
            Opcode::CpAN8 => {},
            Opcode::DecR8(r8) => {},
            Opcode::IncR8(r8) => {},
            Opcode::SbcAR8(r8) => {},
            Opcode::SbcAN8 => {},
            Opcode::SubAR8(r8) => {},
            Opcode::SubAN8 => {},
            Opcode::AddHLR16(r16) => {},
            Opcode::DecR16(r16) => {},
            Opcode::IncR16(r16) => {},
            Opcode::AndAR8(r8) => {},
            Opcode::AndAN8 => {},
            Opcode::Cpl => {},
            Opcode::OrAR8(r8) => {},
            Opcode::OrAN8 => {},
            Opcode::XorAR8(r8) => {},
            Opcode::XorAN8 => {},
            Opcode::Bit(_, r8) => {},
            Opcode::Set(_, r8) => {},
            Opcode::Res(_, r8) => {},
            Opcode::RlR8(r8) => {},
            Opcode::RlA => {},
            Opcode::RlcR8(r8) => {},
            Opcode::RlcA => {},
            Opcode::RrR8(r8) => {},
            Opcode::RrA => {},
            Opcode::RrcR8(r8) => {},
            Opcode::RrcA => {},
            Opcode::SlaR8(r8) => {},
            Opcode::SraR8(r8) => {},
            Opcode::SrlR8(r8) => {},
            Opcode::SwapR8(r8) => {},
            Opcode::CallN16 => {},
            Opcode::CallCCN16(cc) => {},
            Opcode::JpHL => {},
            Opcode::JpN16 => {
                self.registers.pc = mmu.read_16(self.registers.pc.wrapping_add(1));
            },
            Opcode::JpCCN16(cc) => {},
            Opcode::JrE8 => {},
            Opcode::JrCCE8(cc) => {},
            Opcode::Ret => {},
            Opcode::RetCC(cc) => {},
            Opcode::RetI => {},
            Opcode::Rst(_) => {},
            Opcode::Scf => {},
            Opcode::Ccf => {},
            Opcode::AddHLSP => {},
            Opcode::AddSPe8 => {},
            Opcode::LdHLSPe8 => {},
            Opcode::DecSP => {},
            Opcode::IncSP => {},
            Opcode::LdSPN16 => {},
            Opcode::LdPtrN16SP => {},
            Opcode::LdSPHL => {},
            Opcode::PopAF => {},
            Opcode::PopR16(r16) => {},
            Opcode::PushAF => {},
            Opcode::PushR16(r16) => {},
            Opcode::Di => {},
            Opcode::Ei => {},
            Opcode::Halt => {},
            Opcode::Daa => {},
            Opcode::Nop => {
                self.registers.pc += 1;
            },
            Opcode::Stop => {},
            Opcode::Undefined => {},
            Opcode::Prefix => {},
        }
    }
}